<?php

/**
 * BaseRecordComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $record_id
 * @property string $record_type
 * @property string $poster
 * @property string $subject
 * @property clob $body
 * @property BlogPost $BlogPost
 * 
 * @method integer       getId()          Returns the current record's "id" value
 * @method string        getRecordId()    Returns the current record's "record_id" value
 * @method string        getRecordType()  Returns the current record's "record_type" value
 * @method string        getPoster()      Returns the current record's "poster" value
 * @method string        getSubject()     Returns the current record's "subject" value
 * @method clob          getBody()        Returns the current record's "body" value
 * @method BlogPost      getBlogPost()    Returns the current record's "BlogPost" value
 * @method RecordComment setId()          Sets the current record's "id" value
 * @method RecordComment setRecordId()    Sets the current record's "record_id" value
 * @method RecordComment setRecordType()  Sets the current record's "record_type" value
 * @method RecordComment setPoster()      Sets the current record's "poster" value
 * @method RecordComment setSubject()     Sets the current record's "subject" value
 * @method RecordComment setBody()        Sets the current record's "body" value
 * @method RecordComment setBlogPost()    Sets the current record's "BlogPost" value
 * 
 * @package    doctrine_website
 * @subpackage model
 * @author     Jonathan H. Wage
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRecordComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comment');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('record_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('record_type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('poster', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('subject', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             ));


        $this->setAttribute(Doctrine_Core::ATTR_EXPORT, Doctrine_Core::EXPORT_TABLES);
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BlogPost', array(
             'local' => 'record_id',
             'foreign' => 'id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'subject',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggable0);
        $this->actAs($timestampable0);
    }
}