<?php

/**
 * BaseContributor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $nick
 * @property string $role
 * @property string $email
 * @property clob $about
 * @property boolean $core
 * @property boolean $active
 * 
 * @method integer     getId()     Returns the current record's "id" value
 * @method string      getName()   Returns the current record's "name" value
 * @method string      getNick()   Returns the current record's "nick" value
 * @method string      getRole()   Returns the current record's "role" value
 * @method string      getEmail()  Returns the current record's "email" value
 * @method clob        getAbout()  Returns the current record's "about" value
 * @method boolean     getCore()   Returns the current record's "core" value
 * @method boolean     getActive() Returns the current record's "active" value
 * @method Contributor setId()     Sets the current record's "id" value
 * @method Contributor setName()   Sets the current record's "name" value
 * @method Contributor setNick()   Sets the current record's "nick" value
 * @method Contributor setRole()   Sets the current record's "role" value
 * @method Contributor setEmail()  Sets the current record's "email" value
 * @method Contributor setAbout()  Sets the current record's "about" value
 * @method Contributor setCore()   Sets the current record's "core" value
 * @method Contributor setActive() Sets the current record's "active" value
 * 
 * @package    doctrine_website
 * @subpackage model
 * @author     Jonathan H. Wage
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContributor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contributor');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('nick', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('role', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('about', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('core', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggable0);
        $this->actAs($timestampable0);
    }
}