<?php
/*
 * Edit this file to customise your model class
 *
 * auto-generated by the sfDoctrine plugin
 */
class BlogPost extends BaseBlogPost
{
  public function setIsPublished($bool)
  {
    if ($bool !== $this->_get('is_published')) {
      if ($bool && ! $this->_get('created_at')) {
        $this->setCreatedAt(new Doctrine_Expression('NOW()'));
      } else if ( ! $bool) {
        $this->setCreatedAt(null);
      }
      $this->_set('is_published', $bool);
    }
  }

  public function setCreatedAt($createdAt)
  {
    if ($this->_get('created_at') instanceof Doctrine_Expression) {
      return;
    }
    $this->_set('created_at', $createdAt);
  }

  public function filterSetName($name)
  {
    $this->setSlug(Common::createSlug($name));
    
    return $name;
  }

  public function getRecordRoute()
  {
    return $this->getRoute();
  }

  public function getRoute()
  {
    return '@blog_post?slug=' . $this->getSlug();
  }
  
  public function getType()
  {
    return 'Blog Post';
  }

  public function getFormattedBody()
  {
    if (strtotime($this->getCreatedAt()) >= strtotime(date('2008-10-17'))) {
      return DocConverter::renderMarkup($this->_get('body'), 'markdown');
    } else {
      return $this->_get('body');
    }
  }
}