<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Contributor extends BaseContributor
{
  public function getRecordRoute()
  {
    return $this->getRoute();
  }

  public function getRoute()
  {
    return '@contributor?nick=' . $this->getNick();
  }
  
  public function getType()
  {
    return 'Contributor';
  }
}