<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContributorTable extends Doctrine_Table
{
  public function retrieveAboutContributors()
  {
    $q = Doctrine_Query::create()
      ->from('Contributor c')
      ->orderBy('c.core DESC, c.active DESC');

    return $q->execute();
  }
}