<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RecordComment extends BaseRecordComment
{
  public function getTitle()
  {
    return $this->getRecord()->getName() . ' -> ' . $this->getSubject();
  }

  public function getRecordName()
  {
    if ($this->rawGet('record_type') == 'CookbookSection')
    {
      return 'Cookbook Article';
    } else {
      return $this->getRecord()->getType();
    }
  }

  public function getRecord()
  {
    $type = $this->getRecordType();
    if ($type == 'CookbookSection')
    {
      $type = 'ManualSection';
    }
    return $this->$type;
  }
  
  public function getRecordUrl()
  {
    sfContext::getInstance()->getConfiguration()->loadHelpers(array('Url'));
    if ($this->getRecordType() == 'CookbookSection')
    {
      $latest = ApiReleaseTable::getLatest();
      return url_for('@documentation_item_release_chapter?release=' . $latest->getSlug()) . '?chapter=' . $this->getRecord()->getSlug() . '#comment_' . $this->getId();
    } else if ($this->getRecordType() != 'ManualSection' && $this->getRecord()->getRoute()) {
      return url_for($this->getRecord()->getRoute() . '#comment_' . $this->getId());
    } else {
      return $this->getRecord()->getRoute() . '#comment_' . $this->getId();
    }
  }

  public function getRecordRoute()
  {
    if ($this->getRecordType() == 'CookbookSection')
    {
      $latest = ApiReleaseTable::getLatest();
      return '@documentation_item_release_chapter?release=' . $latest->getSlug() . '?chapter=' . $this->getRecord()->getSlug() . '#comment_' . $this->getId();
    } else {
      return $this->getRecord()->getRecordRoute() . '#comment_' . $this->getId();
    }
  }
}