<?php
/*
 * Edit this file to customise your model table
 *
 * auto-generated by the sfDoctrine plugin
 */
class RecordCommentTable extends Doctrine_Table
{
    static public function retrieveRecordComments($record_id, $record_type)
    {
        $query = new Doctrine_Query();
        $query->from('RecordComment c')->where('c.record_id = ? and c.record_type = ?')->orderby('c.created_at asc');

        return $query->execute(array($record_id, $record_type));
    }

    static public function getLatestComments($num = 10)
    {
        $query = new Doctrine_Query();
        $query->from('RecordComment c')->limit($num);
        $query->orderby('c.created_at desc');

        return $query->execute();
    }
}
