<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUser extends PluginsfGuardUser
{
  public function setTableDefinition()
  {
    parent::setTableDefinition();
    $this->hasColumn('email_address', 'string', 255);
  }
}