<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddApiReleaseInfo extends Doctrine_Migration
{
	public function up()
	{
        $this->addColumn('api_release', 'release_manager', 'string', array('length' => 255));
        $this->addColumn('api_release', 'maintained_until', 'date');
        $this->addColumn('api_release', 'stability', 'string', array('length' => 25));
	}

	public function down()
	{
        $this->removeColumn('api_release', 'release_manager');
        $this->removeColumn('api_release', 'maintained_until');
        $this->removeColumn('api_release', 'stability');
	}
}