<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('api_release', 'api_release_project_id_project_id', array(
             'name' => 'api_release_project_id_project_id',
             'local' => 'project_id',
             'foreign' => 'id',
             'foreignTable' => 'project',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('doc_item', 'doc_item_project_id_project_id', array(
             'name' => 'doc_item_project_id_project_id',
             'local' => 'project_id',
             'foreign' => 'id',
             'foreignTable' => 'project',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('api_release', 'api_release_project_id', array(
             'fields' => 
             array(
              0 => 'project_id',
             ),
             ));
        $this->addIndex('doc_item', 'doc_item_project_id', array(
             'fields' => 
             array(
              0 => 'project_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('api_release', 'api_release_project_id_project_id');
        $this->dropForeignKey('doc_item', 'doc_item_project_id_project_id');
        $this->removeIndex('api_release', 'api_release_project_id', array(
             'fields' => 
             array(
              0 => 'project_id',
             ),
             ));
        $this->removeIndex('doc_item', 'doc_item_project_id', array(
             'fields' => 
             array(
              0 => 'project_id',
             ),
             ));
    }
}