<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('project', 'readme', 'string', '255', array());
    }

    public function down()
    {
        $this->removeColumn('project', 'readme');
    }
}