<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('project', 'documentation_link', 'string', '255', array(
             ));
        $this->addColumn('project', 'browse_source_link', 'string', '255', array(
             ));
        $this->addColumn('project', 'api_documentation_link', 'string', '255', array(
             ));
        $this->addColumn('project', 'source_control', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('project', 'documentation_link');
        $this->removeColumn('project', 'browse_source_link');
        $this->removeColumn('project', 'api_documentation_link');
        $this->removeColumn('project', 'source_control');
    }
}