<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/04/20 20:45:45
sfConfig::add(array(
  'app_project_slugs_0' => 'dbal',
  'app_project_slugs_1' => 'orm',
  'app_project_slugs_2' => 'rest',
  'app_project_slugs_3' => 'migrations',
  'app_projects_dbal' => array (
  'title' => 'Database Abstraction Layer',
  'description' => 'Powerful database abstraction layer with many features for database schema introspection, schema management and PDO abstraction.',
),
  'app_projects_orm' => array (
  'title' => 'Object Relational Mapper',
  'description' => 'Object relational mapper (ORM) for PHP 5.2.3+ and 5.3.0+ that sits on top of a powerful database abstraction layer (DBAL). One of its key features is the option to write database queries in a proprietary object oriented SQL dialect called Doctrine Query Language (DQL), inspired by Hibernates HQL. This provides developers with a powerful alternative to SQL that maintains flexibility without requiring unnecessary code duplication.',
),
  'app_projects_rest' => array (
  'title' => 'Database Migrations',
  'description' => 'Easily migrate changes to your databases and version your schema with the Doctrine migrations library.',
),
  'app_projects_migrations' => array (
  'title' => 'REST Server & Client',
  'description' => 'Doctrine REST Server for exposing Doctrine 2 entities as RESTful resources or even raw tables from any existing database using the DBAL.',
),
));
