<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/04/20 20:46:42

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql://root:@localhost/doctrine_website',
  'name' => 'doctrine',
)),);
